// Code generated by mockery v2.8.0. DO NOT EDIT.

package sshkey

import (
	"io/fs"

	"github.com/bitrise-steplib/steps-activate-ssh-key/command"
	"github.com/stretchr/testify/mock"
)

// MockRunnable is an autogenerated mock type for the Runnable type
type MockRunnable struct {
	mock.Mock
}

// PrintableCommandArgs provides a mock function with given fields:
func (_m *MockRunnable) PrintableCommandArgs() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Run provides a mock function with given fields:
func (_m *MockRunnable) Run() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RunAndReturnExitCode provides a mock function with given fields:
func (_m *MockRunnable) RunAndReturnExitCode() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunAndReturnTrimmedOutput provides a mock function with given fields:
func (_m *MockRunnable) RunAndReturnTrimmedOutput() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandBuilder is an autogenerated mock type for the CommandBuilder type
type MockCommandBuilder struct {
	mock.Mock
}

// Command provides a mock function with given fields: name, args, opts
func (_m *MockCommandBuilder) Command(name string, args []string, opts ...command.Opts) command.Runnable {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, name, args)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 command.Runnable
	if rf, ok := ret.Get(0).(func(string, []string, ...command.Opts) command.Runnable); ok {
		r0 = rf(name, args, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(command.Runnable)
		}
	}

	return r0
}

// MockFileWriter is an autogenerated mock type for the FileWriter type
type MockFileWriter struct {
	mock.Mock
}

// Write provides a mock function with given fields: path, value, mode
func (_m *MockFileWriter) Write(path string, value string, mode fs.FileMode) error {
	ret := _m.Called(path, value, mode)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, fs.FileMode) error); ok {
		r0 = rf(path, value, mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTempDirProvider is an autogenerated mock type for the TempDirProvider type
type MockTempDirProvider struct {
	mock.Mock
}

// CreateTempDir provides a mock function with given fields: prefix
func (_m *MockTempDirProvider) CreateTempDir(prefix string) (string, error) {
	ret := _m.Called(prefix)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(prefix)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prefix)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
